---
- hosts: ip-172-31-7-199.ap-south-1.compute.internal 
  become: true
  become_user: root

  tasks:
  - name: Install docker
    package: name=docker state=present

  - name: Start docker
    service: name=docker state=started

  - name: create /opt/myapp
    file: path=/opt/myapp state=directory mode='0777'

  - name: copy docker file
    copy: src=Dockerfile dest=/opt/myapp/

  - name: copy docker file
    copy: src=addressbook.war dest=/opt/myapp/
    
  - name: create docker image using war file
    command: docker build -t myproject:CICD .
    args:
      chdir: /opt/myapp

  - name: create tag to image
    command: docker tag myproject:CICD anwesha988/myproject:CICD

  - name: loginto docker
    command: docker login --username anwesha988 --password Kolkata@1 

  - name: push image on to dockerhub
    command: docker push anwesha988/myproject:CICD
